Histogram
```{r}
trees
hist(trees$Height)
hist( trees$Height, main="Arvores", ylab="Frequência", xlab="Altura", col = "blue")
hist( trees$Height, main="Arvores", ylab="Frequência", xlab="Altura", col = "blue", density = 20, breaks = 20)
```
Density
```{r}
densidade = density(trees$Height)
plot(densidade)
```
Density over Histogram, par
```{r}
#Run with ctrl + shift + enter
hist(trees$Height, main=NULL, xlab=NULL, ylab=NULL)
par(new = TRUE)
plot(densidade)
```
Scatter
```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main="Árvores")
plot(trees$Girth, trees$Volume, ylab = "Circunferência", xlab = "Volume", col = "blue", main = "Árvores")
#pch changes graphical element
plot(trees$Girth, trees$Volume, ylab="Circunferência", xlab = "Volume", col = "blue", main = "Árvores", pch = 20)
```
Changing type with pch
```{r}
plot(trees$Girth, trees$Volume, ylab="Circunferência", xlab = "Volume", col = "blue", main = "Árvores", pch = 20, type ="l")
```
Jitter, decreases over position
```{r}
plot(jitter(trees$Girth), trees$Volume, ylab="Circunferência", xlab = "Volume", col = "blue", main = "Árvores")
```
Legend with categorical dimension
```{r}
#RUN with ctrl + shift + enter
plot(CO2$conc, CO2$uptake,pch=20, col= CO2$Treatment)
#"bottom", "bottomleft", "left", "topleft", "top", "topright", "right" and "center"
legend("bottomright",legend=c("nonchilled","chilled"),cex=1, fill=c("black","red"))  
```
New data
```{r}
plot(trees)
```
Split screen
```{r}
#Run with ctrl + shift + enter
split.screen(figs=c(2,2))
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=TRUE)
```

