```{r}
library(lattice)
```

Boxplot
```{r}
bwplot(trees$Volume)
bwplot(trees$Volume, main="Árvores", xlab="Volume")
```

Histogram(aspect = proportion, nint = breaks, type: percent, count, density)
```{r}
histogram(trees$Volume, main="Árvores", xlab="Volume", aspect=1, type="percent", nint=20)
```

Conditional Histogram
```{r}
chickwts
#histogram
histogram(chickwts$weight)
#aggregate data
aggregate(chickwts$weight, by=list(chickwts$feed), FUN=sum)
#conditional histogram
histogram(~weight | feed, data=chickwts)
```
Conditional scatter graph
CO2, 2 plants in two places, refrigerated or not during the night
```{r}
CO2
xyplot(CO2$conc ~ CO2$uptake)
#type = origin
xyplot(CO2$conc ~ CO2$uptake | CO2$Type)
#Chilled or not
xyplot(CO2$conc ~ CO2$uptake | CO2$Treatment)
```
Esophageal cancer
```{r}
esoph
dotplot(esoph$alcgp ~ esoph$ncontrols, data=esoph)
dotplot(esoph$alcgp ~ esoph$ncontrols | esoph$tobgp)
```
Scatter Plot Matrices
```{r}
splom(~CO2[4:5] | CO2$Type, CO2)
```
Conditional density
```{r}
densityplot(~CO2$conc | CO2$Treatment, plot.points=FALSE)
density(CO2$conc)
densityplot(~CO2$conc | CO2$Treatment)
densityplot(~CO2$conc | CO2$Treatment, plot.points=FALSE)
```
3D chart
```{r}
OrchardSprays
cloud(decrease ~ rowpos * colpos, data=OrchardSprays)
cloud(decrease ~ rowpos * colpos, groups = treatment, data=OrchardSprays)
```
Level plot
```{r}
trees
levelplot(Girth ~ Height * Volume, data=trees)
```
